title: "Barebones Jekyll"
description: "A starter for future jekyll sites."
baseurl: 

markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

exclude: [
  Gemfile*,
  .gitignore,
  README.md
]
